export const SET_ENTITIES = 'SET_ENTITIES';
export const CLEAR_ENTITIES = 'CLEAR_ENTITIES';
export const SET_DOOR_ENTITIES = 'SET_DOOR_ENTITIES';
export const SET_WEATHER_ENTITIES = 'SET_WEATHER_ENTITIES';
export const SET_HOMEPOD_ENTITIES = 'SET_HOMEPOD_ENTITIES';
export const SET_LOADING = 'SET_LOADING';
